substitutions:
  board: d1_mini
  log_level: INFO

esp8266:
  board: ${board}

logger:
  level: ${log_level}

uart:
  baud_rate: 1200
  stop_bits: 2
  tx_pin: GPIO15
  rx_pin: GPIO13

sensor:
  - platform: kamstrup_kmp
    update_interval: 15s
    heat_energy:
      name: Varme energi
      unit_of_measurement: "MWh"
    temp_diff:
      name: Temperatur Difference
      device_class: "temperature"
      unit_of_measurement: "°C"
    flow:
      name: Flow
    temp1:
      name: Fremløb
    temp2:
      name: Returløb
    volume:
      name: Volume
      unit_of_measurement: "m³"
      device_class: water
      state_class: total_increasing
    custom:
      - name: Varme effekt
        command: 0x0050
        unit_of_measurement: "kW"
