substitutions:
  board: d1_mini
  log_level: INFO

esphome:
  friendly_name: ${device_verbose_name}
  name: ${node_name}
  name_add_mac_suffix: true
  project:
    name: mtrab.kamstrup_reader
    version: "1.0"

esp8266:
  board: ${board}

wifi:
  ap:

captive_portal:

api:

ota:
  platform: esphome

dashboard_import:
  package_import_url: github://mtrab/esphome/kamstrup_reader/board_esp8266.yaml@main
  import_full_config: false

logger:
  level: ${log_level}

uart:
  baud_rate: 1200
  stop_bits: 2
  tx_pin: GPIO15
  rx_pin: GPIO13

sensor:
  - platform: kamstrup_kmp
    update_interval: 15s
    heat_energy:
      name: Varme energi
      unit_of_measurement: "MWh"
    temp_diff:
      name: Temperatur Difference
      device_class: "temperature"
      unit_of_measurement: "°C"
    flow:
      name: Flow
    temp1:
      name: Fremløb
    temp2:
      name: Returløb
    volume:
      name: Volume
      unit_of_measurement: "m³"
      device_class: water
      state_class: total_increasing
    custom:
      - name: Varme effekt
        command: 0x0050
        unit_of_measurement: "kW"
